### ISSUE TITLE
Håndtering av SkrSamtykke i bergening av dekningsgrad

### ISSUE THREAD

**Issue by areedv** [Rapporteket/smerte#14]
I tillegg til 0 og 1 inneholder feltet _SkrSamtykke_ også NULL:

![image](https://user-images.githubusercontent.com/1522857/76610341-0f176280-6519-11ea-9379-35966e0e8f31.png)

Andelen/dekningsgraden kan da komme ut som NA etter beregning i R.

**Comment by manjan5** [comment]
Har endret slik at null blir na og tatt med na.rm = TRUE i summen. Bug skal dermed være fikset. Har pushet @areedv .

Har også sjekket QA på helseregister.no (dog uten dette implementert) og det ser ut som det skal! Lett å endre dato også.

**Comment by areedv** [comment]
Ok. Men tror også rapporten feiler om det velges dato utenfor "forventet" intervall, eksempelvis i fremtiden. Det er muligens også et problem når perioden blir veldig kort, eksempelvis enkeltdager der det ikke finnes registreringer. Du får prøve litt spenstige alternativer og sørge for feilhåndtering hhv. Rød tekst på engelsk i rapporten tar seg svært dårlig ut...

**Comment by areedv** [comment]
@manjan5 kan du legge inn dine siste endringer på LokalDekningsgradrapport.Rmd manuelt inn i greina _rel_? Du har tatt utgangspunkt i ei gammel grein (som du sikker har hatt liggende lokalt) men som allerede er merget inn i _rel_ (av meg). Det bør være greit da din endring er liten. Slett deretter din lokale utgave av greina _rapportDekningsgrad_ Tror det blir enklest slik. Om du trenger å se hva som har foregått så kan du ta en titt [her](https://github.com/Rapporteket/smerte/network)

**Comment by manjan5** [comment]
Har nå lagt inn min endring i .Rmd-filen i rel. Har slettet grenen rapportDekningsgrad lokalt og jobber nå i rel. Har kjørt pull og push. Skal greinen slettes her og @areedv?

**Comment by areedv** [comment]
Veldig bra! Jeg har slettet greina _rapportDekningsgrad_. Jeg lager klar en pr til v0.2 og alle endringer vi gjør i _rel_ vil bli inkludert der. Når vi er fornøyde oppdaterer vi _master_, merker/tagger en ny versjon og legger ut i PROD.

Ellers ser jeg en feil i den siste utgaven av _rel_:
![image](https://user-images.githubusercontent.com/1522857/76737639-71ff3880-6769-11ea-8904-ad214df061d2.png)

Jeg tror det skyldes at man forsøker å lage faktorer eller tall av NULL:
```dat$SkrSamtykke <- as.numeric(levels(dat$SkrSamtykke)[dat$SkrSamtykke])```

Det må du gjerne se litt på

**Comment by manjan5** [comment]
Har hatt tekniske problemer i forbindelse med at vi må sitte hjemme. Men nå er jeg i gang. Ser feilen du viser meg der, men den er ikke tilstede hos meg lokalt. Har lagt til include = FALSE i chuncken, som jeg håper skal skjule denne erroren og har pushet endringene. Gir du beskjed når jeg kan sjekke QA @areedv ?

**Comment by areedv** [comment]
Da har jeg lagt ut nyeste versjon i QA

**Comment by manjan5** [comment]
Ser veldig bra ut! Likte endringene i teksten + at det var kommet med antall pasienter totalt og med samtykke. Fikk ingen feil, prøvde dato frem i tid, startdato etter sluttdato og dato med ingen pasienter på.

**Comment by areedv** [comment]
Svært midlertidig versjon lagt ut i QA:
![image](https://user-images.githubusercontent.com/1522857/77291567-d167c600-6cde-11ea-8c20-fe2063af094a.png)
Den er ikke på noe vis ment som en feilretting (av Dekningsgrad) men heller et grunnlag for å finne beste måte å komme videre på.

Ellers er det lagt ut to nye rapporter: metadata og mulighet for nedlasting. Dette bør vi også ta en runde på

**Comment by manjan5** [comment]
Bra fremlegging som gjør ting litt tydeligere. Er det nå også slik at man kun teller med forløp i gjeldende tidsperiode, selv om samtykket er gitt i en annen tidsperiode?

**Comment by areedv** [comment]
Dette er på ingen måte et forsøk på å få dekningsgraden riktig (fordi det kommer an på hva dere faktisk ønsker å vise) men heller en problematisering av hva vi har å forholde oss til. Tror det er lurt at vi tar en prat

**Comment by areedv** [comment]
Da har jeg oppdatert ihht det vi ble enige om. Har også lagt ut på QA men Rapporteket mellomlagrer og viser foreløpig bare forrige utgave. Inntil ny vises der så får du heller se på siste versjon av koden her 9fcfa8db156fff661b3d1d56e9fe05251229695d eller bare siste utgave i greina [dump_metadata](https://github.com/Rapporteket/smerte/tree/dump_metadata)

**Comment by areedv** [comment]
Jeg ser forøvrig at feltet `StartdatoTO` kan inneholde _NULL_ (et tilfelle i det datasettet jeg sitter på fra lokalt register HB). Det er ingen feilhåndtering av dette nå

**Comment by areedv** [comment]
Ser at applikasjonen er oppdatert i QA nå. Du @manjan5 melder ifra når og hvordan vi går videre

**Comment by manjan5** [comment]
Det ser veldig bra ut @areedv. Lars Jørgen har godkjent også. Hadde tenkt å legge til tekst om dekningsgrad, men det du hadde skrevet var akkurat det vi ville ha med. 

Når det gjelder at `startdatoTO` kan inneholde NULL: er det i server.R man må sjekke dette? Kan man legge inn løkker osv på samme måte som i de .Rmd-filene her?

**Comment by areedv** [comment]
Når jeg tenker meg om er det ingen enkel/teknisk fiks av _NULL_ i `StartdatoTO`: det finnes ingen måte å vite noe om NÅR så lenge tidsinformasjonen er tom (_NULL_). Dere må vurdere sannsynligheten for _NULL_ i dette feltet og ut fra det si om vi faktisk kan bruke `StartdatoTO` som et kriterium for utvelgelse av data

**Comment by manjan5** [comment]
Det skal egentlig aldri være _NULL_, og feltet skal alltid fylles ut med en dato uansett om man får tilsyn eller ikke, samtykker eller ikke osv. Men jeg hører nå med Stefanie og Lars Jørgen for sikkerhets skyld. Dersom de er enige går vi videre med dette og da kan vi også legge rapporten ut (i alle fall i følge det jeg vet). Jeg holder deg oppdatert.

**Comment by manjan5** [comment]
Fikk følgende svar fra Stefanie: Startdato i TO skal alltid fylles ut. Siden det er stjerne bak startdatoen er det en obligatorisk variabel som må fylles ut. Dersom det skulle bli glemt, vil man få opp feilmelding ved ferdigstilling av skjema. Så jeg tror at det ikke kan være så enkelt å gjøre feil her.

Så da tenker jeg vi går for dette! @areedv

**Comment by areedv** [comment]
Ok, da kommer det straks en PR som du må gå gjennom
