### ISSUE TITLE
Ny rapport i gren "indiktarorlokal"

### ISSUE THREAD

**Issue by manjan5** [Rapporteket/smerte#19]
@areedv, jeg har nå lagt til en ny rapport i den midlertidige grenen "indikatorlokal". Har i tillegg til rmd-fil prøvd å legge til korrekt info i server.R, ui.R og GetRegData.R, men her er det nok et par ting som må fikses på. 

Dette er (som tilsynsrappporten) en _lokal_ rapport som skal vises _årvis_. Altså at bruker velger mellom år 2016,  år 2017 osv. fra en meny.  Jeg tror jeg har fått til dette med år. I GetRegData.R er det nå left join på avdeling. Dette skal ikke være der (bruker ikke avdeling), men jeg visste ikke helt hvordan kutte det på riktig måte.

Oppsummert: rapporten skal være klar til testing av deg. Det er en lokal rapport som skal sortere på år. Filene server.R, ui.R og GetRegData.R er forsøkt ryddet opp i, men det trengs en gjennomgang av deg.

**Comment by areedv** [comment]
Ok, jeg skal gå gjennom dette så snart jeg er ledig

**Comment by manjan5** [comment]
Supert. Et spørsmål til: vi skal legge ut en tilsvarende rapport til den lokale, men på den nasjonale siden. Det vil si at variablene vi ser på er de samme, men tallene vi bruker er de nasjonale og vi sammenligner da også på  sykehusnivå. Jeg har klart et utkast til denne også. Er det best om vi også arbeider med denne samtidig (i denne grenen) eller bør den håndteres separat?

**Comment by areedv** [comment]
Jeg syns det kan få sin egen grein. Syns det blir mer orden sånn

**Comment by manjan5** [comment]
@areedv 

Figurer og tekst ordnet i gren indikatorlokal. I gren lasteDatadump har jeg som du vil se forsøkt å legge til nedlasting av datadump (5 ulike tabeller).
