### ISSUE TITLE
Ny rapport i gren "indiktarornasjonal"

### ISSUE THREAD

**Issue by manjan5** [Rapporteket/smerte#20]
Tilsvarende som issue #19 , men denne skal ligge på det nasjonale rapporteket.

Har kun lagt til rmd-fil, ettersom jeg ikke visste om endringene i server og ui blir annerledes for nasjonale tall. Det er kanskje bare avhengig av tilgangen?

Ellers likt som for lokale tall, skal vises årvis. Året velges av bruker.

Oppsummert: rapporten skal være klar til testing av deg. Det er en nasjonal rapport som skal sortere på år. Filene server.R, ui.R og GetRegData.R trengs en gjennomgang av deg, @areedv.

**Comment by areedv** [comment]
Slått sammen med og fortsetter i #19
