### ISSUE TITLE
Rydd opp avhengigheter (samlerapporter)

### ISSUE THREAD

**Issue by areedv** [Rapporteket/smerte#24]
Vanskelig å holde oversikt når det i koden ikke benyttes eksplisitte referanser til pakker som er brukt.

Når R pakker lastes i starten bør kun de som benyttes føres opp. Pakken 'tidyverse' tar potensielt med mange flere pakker enn det som trengs og det representerer en tidskostnad ved kjøring av applikasjon samt ved feilsøk

> library(tidyverse)
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
✔ ggplot2 3.3.2     ✔ purrr   0.3.4
✔ tibble  3.0.3     ✔ stringr 1.4.0
✔ tidyr   1.1.0     ✔ forcats 0.5.0
✔ readr   1.3.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

**Comment by manjan5** [comment]
Takk for tips. Skal rydde opp i dette!

**Comment by areedv** [comment]
Need enforcing throughout. To be followed up continuously
