### ISSUE TITLE
Tabell- og figurfanen

### ISSUE THREAD

**Issue by manjan5** [Rapporteket/smerte#5]
@areedv , tenkte å lage et eksempel med smertedata under denne fanen som vi snakket om. Har noen spørsmål rundt dette.

1. Plott og tabell genereres vel i server.ui linje 131-141 og bruker regData, som er testdatasettet. Dersom jeg skal bruke vårt datasett, er dette allerede "lastet inn"? Eller må jeg f.eks. hente inn: getRegDataLokalTilsynsrapportMaaned(registryName = "smerte",
                                             reshId = params$reshId,
                                             year = params$year,
                                             session=session)
og deretter velge f.eks "var = input$smertevariabel"

Lurer vel generelt på hvordan å endre dette. Kan eventuelt snakkes over telefon!

**Comment by areedv** [comment]
Sitter opptatt akkurat nå... Svarer så raskt jeg er på hold

**Comment by areedv** [comment]
```regData``` defineres i linje 10. Den kan du erstatte med det samme som du har i samledokumentet (lokalt tilsyn), altså
```r
if (context %in% c("DEV", "TEST", "QA", "PRODUCTION")) {
  dat <- getRegDataLokalTilsynsrapportMaaned(registryName = "smerte",
                                             reshId = params$reshId,
                                             year = params$year,
                                             session=session)
} else {
  #Dataimport: skal hente lokale data for hvert sykehus (tar vekk sti, og erstatter med lokal filB)
  path <- read.csv(file = "H:/path.csv", header = FALSE, sep = ";")
  path <- as.data.frame(lapply(path, as.character), stringsAsFactors=FALSE)
  path <- path$V1
  dat <- read.csv(file = path, header = TRUE, sep = ";")
  
  avdpath <- read.csv(file = "H:/avdelingpath.csv", header = FALSE, sep = ";")
  avdpath <- as.data.frame(lapply(avdpath, as.character), stringsAsFactors=FALSE)
  avdpath <- avdpath$V1
  avd <- read.csv(file = avdpath, header = TRUE, sep = ";", encoding = "UTF-8")
  #Endrer navn til å matche rapporteket
  avd <- avd %>% rename(DEPARTMENT_ID = AvdID, DEPARTMENT_NAME = AvdNavn, DEPARTMENT_SHORTNAME = AvdNavnKort)

  #Samler datasettene vha InnlAvd i allevarnum og departmentID i avdelingsoversikt
  dat <- merge(x = dat, y = avd, by.x = c("InnlAvd"), by.y = c("DEPARTMENT_ID"))

  #Må kunne laste inn data for de ulike årene
  aar <- params$year
  dat = dat %>% filter(year(date(RegDato11)) == aar) #year

}
```

**Comment by areedv** [comment]
Jeg har endret litt på forrige post (bare i tilfelle du nå plages med min opprinnelige kode)...

**Comment by areedv** [comment]
Jeg ser at dette ikke svarer veldig godt på det du spør om. Tror vi tar en prat heller...

**Comment by areedv** [comment]
Gammel og muligens utdatert
