### ISSUE TITLE
Legg til rapport "Dekningsgrad"

### ISSUE THREAD

**Issue by areedv** [Rapporteket/smerte#9]
Ny rapport. I tilfelle dette er ett tall (!) så kan det hende denne heller bør inn som et nøkkeltall/tabell på førsteside (som nå heter "Veiledning")

**Comment by areedv** [comment]
![image](https://user-images.githubusercontent.com/1522857/73648966-06f91700-467f-11ea-83b1-ec3dced9e349.png)

![image](https://user-images.githubusercontent.com/1522857/73648992-1710f680-467f-11ea-8191-59cf68f7f04f.png)

**Comment by manjan5** [comment]
Det er bare ett tall, ja (men som endres etter tidsperiode)! Kan jeg bare endre forsiden og legge den direkte inn der? Kan vi fortsatt ha datovalg på forsiden? Og at den kun vises lokalt?

**Comment by areedv** [comment]
![image](https://user-images.githubusercontent.com/1522857/73650259-0615b480-4682-11ea-9450-0a52efd91a49.png)

---

![image](https://user-images.githubusercontent.com/1522857/73650286-162d9400-4682-11ea-9a07-2b75be56bbfe.png)

**Comment by areedv** [comment]
Det kan ev legges ut som en tabell på forsida der hver rad er en relevant tidsperiode, eksempelvis. Og, ja, det er ingen problem å vise dette kun når brukere representerer et lokalt register

**Comment by manjan5** [comment]
Akkurat slik jeg så det for meg. Hva mangler fra min side for å få dette til?

**Comment by areedv** [comment]
Det bør vel testes litt... Overskrifta i pdf-en ser litt rar ut også... Når du er fornøyd gjøres en merge til 'rel' (og 'rapportDekningsgrad' slettes). Deretter (og muligens sammen med andre endriner) gjøres en pull request til 'master' til en ny versjon 0.2 og legges i PROD

**Comment by manjan5** [comment]
OK. Kan forresten være greit at den kan lastes ned, for LJ er avhengig av at de "lokale" ved andre sykehus sender ham tall som skal brukes i årsrapport etc. Og da tror jeg det er ok å kunne sende et ferdig dokument. 

Vil gjerne teste mer. Der jeg står litt fast er hva som skal inn i server.r / ui.r som gjør at jeg kan teste det hele hos meg. Altså at jeg kan trykke "run app" og at hele siden kommer opp.

**Comment by manjan5** [comment]
Edit: ser at du har endret de nå nå!

**Comment by manjan5** [comment]
Får følgende melding i selve shiny-vinduet: _ERROR: unused argument (addUserInfo = TRUE)_
og i R console får jeg: _Attaching package: ‘shinyalert’

The following object is masked from ‘package:shiny’:

    runExample

Warning: Error in appNavbarUserWidget: unused argument (addUserInfo = TRUE)
  56: tag
  55: tags$div
  54: div
  53: mainPanel_

Har du vært borti dette?

**Comment by areedv** [comment]
Hm, mulig du har en (for) gammel versjon av rapbase... Du kan i alle fall prøve ```remotes::install_github("Rapporteket/rapbase")```

**Comment by manjan5** [comment]
Det løste det problemet. Nå dukker siden opp, og jeg rekker å se alle fanene (overskriftene), men så lukkes siden og i R-console kommer:

**Comment by manjan5** [comment]
Det virket! Det som skjer nå er at siden kommer frem, og jeg rekker å se alle fanene og at dekningsgrad er kommet med. Men så lukker siden seg og følgende kommer i R-console: Warning: Error in appendLog: There is nowhere to append the logging event. The environment variable R_RAP_CONFIG_PATH should be defined!

Det virker jo til å stå hva feilen er og at det gjelder server.R, men jeg skjønner ikke så mye likevel. Har du en ide?

**Comment by areedv** [comment]
Du mangler et relevant utviklingsmiljø, og feilen du får skyldes altså dette. Du kan komme et steg videre ved å definere miljøvariabelen R_RAP_CONFIG_PATH="C:\sti\til\min\mappe" (hvis du bruker windows). Men du vil nok renne i flere feil hvis du ikke har data tilgjengelig (men det har du kanskje?)

Det er også mulig at du må definere miljøvariabelen R_RAP_INSTANCE="DEV" også.

Vi tilbyr altså et fullverdig utviklingsmiljø (simulering av Rapporteket) i form av en Docker container men Helse Bergen er tilbakeholden med å la egne ansatte ta dette i bruk. Dette hindere da effektiv jobbing med utvikling av innhold i Rappoteket, bla for Smerteregisteret
